In [57]:
import pandas as pd

In [58]:
top3 = pd.read_csv("top3.csv")

In [59]:
top3.shape

(39018, 15)

In [60]:
top3.isna().sum()

permalink                      0
name                           0
homepage_url                1857
category_list                215
status                         0
country_code                   0
state_code                    73
region                       158
city                         158
founded_at                  6326
funding_round_permalink        0
funding_round_type             0
funding_round_code         17816
funded_at                      0
raised_amount_usd              0
dtype: int64

In [61]:
top3.category_list.value_counts()

Biotechnology                                                        4633
Software                                                             3238
Health Care                                                          1224
Clean Technology                                                     1040
Enterprise Software                                                  1012
                                                                     ...
Consulting|Health and Wellness|Health Care|Hospitals                    1
Development Platforms|Games|Software                                    1
Events                                                                  1
All Markets|Auctions|Business Services|E-Commerce|Internet|Search       1
Early-Stage Technology|Energy Efficiency|Fuels                          1
Name: category_list, Length: 7798, dtype: int64

In [62]:
mapping = pd.read_csv("mapping.csv")

In [63]:
mapping

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,NaN,0,1,0,0,0,0,0,0,0
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
683,Wholesale,0,0,0,0,0,0,0,1,0
684,Wine And Spirits,0,0,0,1,0,0,0,0,0
685,Wireless,0,0,0,1,0,0,0,0,0
686,Women,0,0,0,0,0,0,0,1,0
687,Young Adults,0,0,0,0,0,0,0,1,0

In [64]:
mapping.category_list.value_counts()

Cable                          1
Enterprises                    1
Discounts                      1
Small and Medium Businesses    1
Business Productivity          1
                              ..
Cloud-Based Music              1
Call Center Automation         1
Building Owners                1
Baby Boomers                   1
Aquaculture                    1
Name: category_list, Length: 687, dtype: int64

In [65]:
mapping[mapping.category_list == "Hardware + Software"]

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
323,Hardware + Software,0,0,0,0,0,1,0,0,0

In [66]:
top3.isnull().sum()

permalink                      0
name                           0
homepage_url                1857
category_list                215
status                         0
country_code                   0
state_code                    73
region                       158
city                         158
founded_at                  6326
funding_round_permalink        0
funding_round_type             0
funding_round_code         17816
funded_at                      0
raised_amount_usd              0
dtype: int64

In [67]:
top3 = top3[~top3.category_list.isnull()]

In [68]:
top3.shape

(38803, 15)

In [69]:
top3.isnull().sum()

permalink                      0
name                           0
homepage_url                1792
category_list                  0
status                         0
country_code                   0
state_code                    72
region                       156
city                         156
founded_at                  6178
funding_round_permalink        0
funding_round_type             0
funding_round_code         17720
funded_at                      0
raised_amount_usd              0
dtype: int64

In [70]:
mapping = mapping[1:]

In [71]:
mapping.shape

(687, 10)

In [72]:
mapping

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1
5,Active Lifestyle,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
683,Wholesale,0,0,0,0,0,0,0,1,0
684,Wine And Spirits,0,0,0,1,0,0,0,0,0
685,Wireless,0,0,0,1,0,0,0,0,0
686,Women,0,0,0,0,0,0,0,1,0
687,Young Adults,0,0,0,0,0,0,0,1,0

In [73]:
mapping = mapping.drop(columns=["Blanks"])

In [74]:
mapping

,category_list,Automotive & Sports,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
1,3D,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,1
5,Active Lifestyle,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
683,Wholesale,0,0,0,0,0,0,1,0
684,Wine And Spirits,0,0,1,0,0,0,0,0
685,Wireless,0,0,1,0,0,0,0,0
686,Women,0,0,0,0,0,0,1,0
687,Young Adults,0,0,0,0,0,0,1,0

In [75]:
categories = list(mapping.category_list)

In [76]:
categories

['3D',
 '3D Printing',
 '3D Technology',
 'Accounting',
 'Active Lifestyle',
 'Ad Targeting',
 'Advanced Materials',
 'Adventure Travel',
 'Advertising',
 'Advertising Exchanges',
 'Advertising Networks',
 'Advertising Platforms',
 'Advice',
 'Aerospace',
 'Agriculture',
 'Air Pollution Control',
 'Algorithms',
 'All Markets',
 'All Students',
 'Alter0tive Medicine',
 'Alumni',
 'A0lytics',
 'Android',
 'Angels',
 'Animal Feed',
 'Anything Capital Intensive',
 'App Discovery',
 'App Marketing',
 'App Stores',
 'Application Performance Monitoring',
 'Application Platforms',
 'Apps',
 'Aquaculture',
 'Architecture',
 'Archiving',
 'Art',
 'Artificial Intelligence',
 'Artists Globally',
 'Assisitive Technology',
 'Assisted Living',
 'Auctions',
 'Audio',
 'Audiobooks',
 'Augmented Reality',
 'Auto',
 'Automated Kiosk',
 'Automotive',
 'B2B',
 'B2B Express Delivery',
 'Babies',
 'Baby Accessories',
 'Baby Boomers',
 'Baby Safety',
 'Banking',
 'Batteries',
 'Beauty',
 'Bicycles',
 'Big Data',
 'Big Data A0lytics',
 'Billing',
 'Bio-Pharm',
 'Biofuels',
 'Bioinformatics',
 'Biomass Power Generation',
 'Biometrics',
 'Biotechnology',
 'Bitcoin',
 'Blogging Platforms',
 'Boating Industry',
 'BPO Services',
 'Brand Marketing',
 'Brewing',
 'Bridging Online and Offline',
 'Broadcasting',
 'Brokers',
 'Browser Extensions',
 'Building Owners',
 'Building Products',
 'Business A0lytics',
 'Business Development',
 'Business Information Systems',
 'Business Intelligence',
 'Business Productivity',
 'Business Services',
 'Business Travelers',
 'Cable',
 'CAD',
 'Call Center Automation',
 'Can0bis',
 'Carbon',
 'Career Ma0gement',
 'Career Planning',
 'Cars',
 'Casual Games',
 'Celebrity',
 'Certification Test',
 'Charities',
 'Charity',
 'Charter Schools',
 'Chat',
 'Chemicals',
 'Child Care',
 'Chi0 Internet',
 'Civil Engineers',
 'Classifieds',
 'Clean Energy',
 'Clean Technology',
 'Clean Technology IT',
 'Clinical Trials',
 'Cloud-Based Music',
 'Cloud Computing',
 'Cloud Data Services',
 'Cloud Infrastructure',
 'Cloud Ma0gement',
 'Cloud Security',
 'Coffee',
 'Collaboration',
 'Collaborative Consumption',
 'Collectibles',
 'College Campuses',
 'College Recruiting',
 'Colleges',
 'Comics',
 'Commercial Real Estate',
 'Commercial Solar',
 'Commodities',
 'Communications Hardware',
 'Communications Infrastructure',
 'Communities',
 'Comparison Shopping',
 'Computer Vision',
 'Computers',
 'Concentrated Solar Power',
 'Concerts',
 'Console Gaming',
 'Construction',
 'Consulting',
 'Consumer Behavior',
 'Consumer Electronics',
 'Consumer Goods',
 'Consumer Internet',
 'Consumer Lending',
 'Consumers',
 'Contact Centers',
 'Contact Ma0gement',
 'Content',
 'Content Creators',
 'Content Delivery',
 'Content Discovery',
 'Content Syndication',
 'Contests',
 'Cooking',
 'Corporate IT',
 'Corporate Training',
 'Corporate Wellness',
 'Cosmetic Surgery',
 'Cosmetics',
 'Coupons',
 'Coworking',
 'Craft Beer',
 'Creative',
 'Creative Industries',
 'Credit',
 'Credit Cards',
 'CRM',
 'Crowdfunding',
 'Crowdsourcing',
 'Curated Web',
 'Custom Retail',
 'Customer Service',
 'Customer Support Tools',
 'Cyber',
 'Cyber Security',
 'Data Center Automation',
 'Data Center Infrastructure',
 'Data Centers',
 'Data Integration',
 'Data Mining',
 'Data Privacy',
 'Data Security',
 'Data Visualization',
 'Databases',
 'Debt Collecting',
 'Defense',
 'Delivery',
 'Demographies',
 'Dental',
 'Design',
 'Designers',
 'Developer APIs',
 'Developer Tools',
 'Development Platforms',
 'Diabetes',
 'Diagnostics',
 'Dietary Supplements',
 'Digital Entertainment',
 'Digital Media',
 'Digital Rights Ma0gement',
 'Digital Sig0ge',
 'Direct Advertising',
 'Direct Marketing',
 'Direct Sales',
 'Discounts',
 'Displays',
 'Disruptive Models',
 'Distribution',
 'Distributors',
 'DIY',
 'Doctors',
 'Document Ma0gement',
 'DOD/Military',
 'Domains',
 'Drones',
 'E-Books',
 'E-Commerce',
 'E-Commerce Platforms',
 'Early-Stage Technology',
 'EBooks',
 'EDA Tools',
 'Ediscovery',
 'EdTech',
 'Education',
 'Educatio0l Games',
 'Edutainment',
 'Elder Care',
 'Electric Vehicles',
 'Electrical Distribution',
 'Electronic Health Records',
 'Electronics',
 'Email',
 'Email Marketing',
 'Email Newsletters',
 'Embedded Hardware and Software',
 'Emerging Markets',
 'Employer Benefits Programs',
 'Employment',
 'Energy',
 'Energy Efficiency',
 'Energy IT',
 'Energy Ma0gement',
 'Energy Storage',
 'Engineering Firms',
 'Enterprise 2.0',
 'Enterprise Application',
 'Enterprise Purchasing',
 'Enterprise Resource Planning',
 'Enterprise Search',
 'Enterprise Security',
 'Enterprise Software',
 'Enterprises',
 'Entertainment',
 'Entertainment Industry',
 'Entrepreneur',
 'Environmental Innovation',
 'Estimation and Quoting',
 'Event Ma0gement',
 'Events',
 'Exercise',
 'Eyewear',
 'Face Recognition',
 'Facebook Applications',
 'Families',
 'Fantasy Sports',
 'Farmers Market',
 'Farming',
 'Fashion',
 'Fertility',
 'Field Support Services',
 'File Sharing',
 'Film',
 'Film Distribution',
 'Film Production',
 'Fi0nce',
 'Fi0nce Technology',
 'Fi0ncial Exchanges',
 'Fi0ncial Services',
 'FinTech',
 'Fitness',
 'Flash Sales',
 'Flash Storage',
 'Fleet Ma0gement',
 'Flowers',
 'Fmcg',
 'Food Processing',
 'Forums',
 'Fraud Detection',
 'Freelancers',
 'Freemium',
 'FreetoPlay Gaming',
 'Fruit',
 'Fuel Cells',
 'Fuels',
 'Funeral Industry',
 'Furniture',
 'Gadget',
 'Gambling',
 'Game',
 'Game Mechanics',
 'Games',
 'Gamification',
 'Gas',
 'Gay & Lesbian',
 'General Public Worldwide',
 'Genetic Testing',
 'Geospatial',
 'Gift Card',
 'Gift Exchange',
 'Gift Registries',
 'Gold',
 'Gover0nce',
 'Government Innovation',
 'Governments',
 'Gps',
 'Graphics',
 'Green',
 'Green Consumer Goods',
 'Groceries',
 'Group Buying',
 'Group SMS',
 'Guides',
 'Handmade',
 'Hardware',
 'Hardware + Software',
 'Health and Insurance',
 'Health and Wellness',
 'Health Care',
 'Health Care Information Technology',
 'Health Diagnostics',
 'Health Services Industry',
 'Healthcare Services',
 'Heavy Industry',
 'Hedge Funds',
 'High School Students',
 'High Schools',
 'High Tech',
 'Home & Garden',
 'Home Automation',
 'Home Decor',
 'Home Owners',
 'Home Renovation',
 'Homeland Security',
 'Homeless Shelter',
 'Hospitality',
 'Hospitals',
 'Hotels',
 'Human Computer Interaction',
 'Human Resource Automation',
 'Human Resources',
 'Humanitarian',
 'IaaS',
 'ICT',
 'Identity',
 'Identity Ma0gement',
 'Image Recognition',
 'Impact Investing',
 'In-Flight Entertainment',
 'Incentives',
 'Incubators',
 'Independent Music Labels',
 'Independent Pharmacies',
 'Indians',
 'Indoor Positioning',
 'Industrial',
 'Industrial Automation',
 'Information Security',
 'Information Services',
 'Information Technology',
 'Infrastructure',
 'Innovation Engineering',
 'Innovation Ma0gement',
 'Insurance',
 'Intellectual Asset Ma0gement',
 'Intellectual Property',
 'Intelligent Systems',
 'Interest Graph',
 'Interface Design',
 'Interior Design',
 'Internet',
 'Internet Infrastructure',
 'Internet Marketing',
 'Internet of Things',
 'Internet Radio Market',
 'Internet Service Providers',
 'Investment Ma0gement',
 'iOS',
 'iPad',
 'iPhone',
 'IT and Cybersecurity',
 'IT Ma0gement',
 'Jewelry',
 'Jour0lism',
 'K-12 Education',
 'Kids',
 'Knowledge Ma0gement',
 'Landscaping',
 'Language Learning',
 'Lasers',
 'Law Enforcement',
 'Lead Generation',
 'Lead Ma0gement',
 'Legal',
 'Leisure',
 'Licensing',
 'Life Sciences',
 'Lifestyle',
 'Lifestyle Businesses',
 'Lifestyle Products',
 'Lighting',
 'Limousines',
 'Linux',
 'Local',
 'Local Advertising',
 'Local Based Services',
 'Local Businesses',
 'Local Commerce',
 'Local Search',
 'Location Based Services',
 'Logistics',
 'Logistics Company',
 'Lotteries',
 'Low Bid Auctions',
 'Loyalty Programs',
 'M2M',
 'Machine Learning',
 'Manufacturing',
 'Maps',
 'Market Research',
 'Marketing Automation',
 'Marketplaces',
 'Mass Customization',
 'Match-Making',
 'Material Science',
 'Mechanical Solutions',
 'Media',
 'Medical',
 'Medical Devices',
 'Medical Professio0ls',
 'Meeting Software',
 'Mens Specific',
 'Messaging',
 'mHealth',
 'Micro-Enterprises',
 'MicroBlogging',
 'Minerals',
 'Mining Technologies',
 'Mobile',
 'Mobile Advertising',
 'Mobile A0lytics',
 'Mobile Commerce',
 'Mobile Devices',
 'Mobile Enterprise',
 'Mobile Games',
 'Mobile Health',
 'Mobile Infrastructure',
 'Mobile Payments',
 'Mobile Security',
 'Mobile Shopping',
 'Mobile Social',
 'Mobile Software Tools',
 'Mobile Video',
 'Mobility',
 'Monetization',
 'Moneymaking',
 'Multi-level Marketing',
 'Music',
 'Music Education',
 'Music Services',
 'Music Venues',
 'Musical Instruments',
 'Musicians',
 '0notechnology',
 '0tural Language Processing',
 '0tural Resources',
 '0vigation',
 'Network Security',
 'Networking',
 'Neuroscience',
 'New Product Development',
 'New Technologies',
 'News',
 'Non-Tech',
 'Non Profit',
 'Nonprofits',
 'Nutrition',
 'Office Space',
 'Oil',
 'Oil & Gas',
 'Oil and Gas',
 'Online Dating',
 'Online Education',
 'Online Gaming',
 'Online Identity',
 'Online Rental',
 'Online Reservations',
 'Online Scheduling',
 'Online Shopping',
 'Online Travel',
 'Online Video Advertising',
 'Open Source',
 'Opinions',
 'Optical Communications',
 'Optimization',
 'Organic',
 'Organic Food',
 'Outdoors',
 'Outsourcing',
 'P2P Money Transfer',
 'PaaS',
 'Parenting',
 'Parking',
 'Payments',
 'Peer-to-Peer',
 'Performance Marketing',
 'Perso0l Branding',
 'Perso0l Data',
 'Perso0l Fi0nce',
 'Perso0l Health',
 'Perso0lization',
 'Pervasive Computing',
 'Pets',
 'Pharmaceuticals',
 'Photo Editing',
 'Photo Sharing',
 'Photography',
 'Physical Security',
 'Physicians',
 'Plumbers',
 'Point of Sale',
 'Politics',
 'Polling',
 'Portals',
 'Postal and Courier Services',
 'Pre Seed',
 'Predictive A0lytics',
 'Presentations',
 'Price Comparison',
 'Printing',
 'Privacy',
 'Private School',
 'Private Social Networking',
 'Procurement',
 'Product Design',
 'Product Development Services',
 'Productivity',
 'Productivity Software',
 'Professio0l Networking',
 'Professio0l Services',
 'Project Ma0gement',
 'Promotio0l',
 'Property Ma0gement',
 'Public Relations',
 'Public Safety',
 'Public Transportation',
 'Publishing',
 'Q&A',
 'QR Codes',
 'Real Estate',
 'Real Time',
 'Realtors',
 'Recreation',
 'Recruiting',
 'Recycling',
 'Religion',
 'Renewable Energies',
 'Renewable Tech',
 'Rental Housing',
 'Reputation',
 'Resorts',
 'Restaurants',
 'Retail',
 'Retail Technology',
 'Reviews and Recommendations',
 'RFID',
 'Ride Sharing',
 'Risk Ma0gement',
 'Robotics',
 'SaaS',
 'Sales and Marketing',
 'Sales Automation',
 'Search',
 'Search Marketing',
 'Security',
 'Semiconductor Manufacturing Equipment',
 'Semiconductors',
 'Senior Citizens',
 'Senior Health',
 'Sensors',
 'SEO',
 'Service Industries',
 'Service Providers',
 'Services',
 'SexTech',
 'Shared Services',
 'Shipping',
 'Shoes',
 'Shopping',
 'Simulation',
 'Skill Assessment',
 'Small and Medium Businesses',
 'Smart Grid',
 'SNS',
 'Soccer',
 'Social + Mobile + Local',
 'Social Bookmarking',
 'Social Business',
 'Social Buying',
 'Social Commerce',
 'Social CRM',
 'Social Fundraising',
 'Social Games',
 'Social Media',
 'Social Media Ma0gement',
 'Social Media Marketing',
 'Social Media Platforms',
 'Social Network Media',
 'Social News',
 'Social Recruiting',
 'Social Television',
 'Social Travel',
 'Software',
 'Solar',
 'Space Travel',
 'Specialty Chemicals',
 'Specialty Foods',
 'Speech Recognition',
 'Sporting Goods',
 'Sports',
 'Staffing Firms',
 'Startups',
 'Stock Exchanges',
 'Storage',
 'Subscription Service',
 'Supply Chain Ma0gement',
 'Surveys',
 'Synchronization',
 'Systems',
 'Task Ma0gement',
 'Taxis',
 'Tea',
 'Technology',
 'Telecommunications',
 'Television',
 'Textiles',
 'Theatre',
 'Therapeutics',
 'Ticketing',
 'Tourism',
 'Tracking',
 'Trading',
 'Training',
 'Translation',
 'Transportation',
 'Travel',
 'Travel & Tourism',
 'Universities',
 'University Students',
 'Unmanned Air Systems',
 'Usability',
 'User Experience Design',
 'User Interface',
 'Utilities',
 'Vending and Concessions',
 'Venture Capital',
 'Veteri0ry',
 'Video',
 'Video Conferencing',
 'Video Games',
 'Video on Demand',
 'Video Streaming',
 'Virtual Workforces',
 'VoIP',
 'Waste Ma0gement',
 'Watch',
 'Water',
 'Water Purification',
 'Wearables',
 'Web Browsers',
 'Web Design',
 'Web Development',
 'Web Hosting',
 'Web Tools',
 'Weddings',
 'Wholesale',
 'Wine And Spirits',
 'Wireless',
 'Women',
 'Young Adults']

In [77]:
import numpy as np

In [78]:
def isMainCategory(category):
    subs = category.split("|")
    tot = np.sum([True for x in subs if x in categories])
    return True if tot > 0 else False

In [79]:
top3

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0
2,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0
3,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0
4,/organization/1-mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39013,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0
39014,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0
39015,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0
39016,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0
39017,/organization/zystor,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0

In [80]:
top3MainCategories = top3[top3.category_list.apply(lambda x : isMainCategory(x))]

In [81]:
top3MainCategories.shape

(37999, 15)

In [82]:
top3.shape

(38803, 15)

In [83]:
top3.category_list.apply(lambda x : x.split('|')[0])

0                Media
1            Analytics
2            Analytics
3            Analytics
4                 Apps
             ...
39013    Biotechnology
39014    Biotechnology
39015    Biotechnology
39016       E-Commerce
39017    Biotechnology
Name: category_list, Length: 38803, dtype: object

In [84]:
top3['primary_sector'] = top3.category_list.apply(lambda x : x.split('|')[0])

In [85]:
top3

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,primary_sector
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,Media
1,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0,Analytics
2,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0,Analytics
3,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0,Analytics
4,/organization/1-mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0,Apps
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39013,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0,Biotechnology
39014,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0,Biotechnology
39015,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0,Biotechnology
39016,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0,E-Commerce
39017,/organization/zystor,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0,Biotechnology

In [86]:
top3.primary_sector.value_counts()

Biotechnology          5875
Software               3345
Advertising            1847
Health Care            1596
Enterprise Software    1560
                       ...
Presentations             1
Mens Specific             1
Material Science          1
Debt Collecting           1
Water                     1
Name: primary_sector, Length: 563, dtype: int64

In [87]:
mapping.head()

,category_list,Automotive & Sports,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
1,3D,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,1
5,Active Lifestyle,0,0,0,1,0,0,0,0

In [88]:
def getMainSector(primary_sector):
    entry = mapping[mapping.category_list == primary_sector]
    return [x for x in entry.columns if (entry.loc[:,x] == 1).values[0]][0]

In [89]:
getMainSector("Accounting")

'Social, Finance, Analytics, Advertising'

In [90]:
main_sectors = mapping.category_list.values

In [91]:
'Active Lifestyle' in main_sectors

True

In [92]:
top3['primary_sector'] = top3.category_list.apply(lambda x : x.split('|')[0])

In [93]:
top3MC = top3[top3.primary_sector.isin(main_sectors)]

In [94]:
top3MC

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,primary_sector
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,Media
4,/organization/1-mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0,Apps
5,/organization/10-minutes-with,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0,Education
6,/organization/1000memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,A,16-02-2011,2520000.0,Curated Web
7,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008,/funding-round/13be128d655076a025221d7fddc90d68,venture,NaN,14-10-2009,265940.0,Curated Web
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39013,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0,Biotechnology
39014,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0,Biotechnology
39015,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0,Biotechnology
39016,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0,E-Commerce
39017,/organization/zystor,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0,Biotechnology

In [ ]:
top3MC['main_sector'] = top3MC.primary_sector.apply(lambda x : getMainSector(x))

In [ ]:
top3MC

In [ ]:
top3MC.isnull().sum()

In [ ]:
top3MC.to_csv("top3MC.csv", index=False)

In [ ]:
top3MC.main_sector.value_counts()

In [ ]:
top3MC.country_code.value_counts()

In [ ]:
USA = top3MC[top3MC.country_code == 'USA']

In [ ]:
GBR = top3MC[top3MC.country_code == 'GBR']

In [ ]:
IND = top3MC[top3MC.country_code == 'IND']

In [ ]:
USA.to_csv('USA.csv', index=False)

In [ ]:
GBR.to_csv('GBR.csv', index=False)

In [ ]:
IND.to_csv('IND.csv', index=False)